platform :ios, '9.0'

target 'Example' do
  use_frameworks!
  pod 'DynamsoftbarcodereaderSDk', :git => 'https://github.com/zyunique/DynamsoftbarcodereaderSDK.git', :branch => '7.2.0'

  target 'Example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Example-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-tvOS

end
